### ISSUE TITLE
Request cancelled before getting any data

### ISSUE THREAD

**Issue by dams2007** [cmoulton/SwiftParseDemo#1]
Hi Christina, first thanks for this project. I setup everything to give a try to your project, but looks like the data call is cancelled. I got access to my keys, and everything is fine with Parse. But I got this error : "Optional(Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo=0x7fa2c8e5bfb0 {NSErrorFailingURLKey=https://api.parse.com/1/classes/Products/, NSLocalizedDescription=cancelled, NSErrorFailingURLStringKey=https://api.parse.com/1/classes/Products/})"

I checked a bit and looks like the problem is coming from Alamofire, I found a similar problem here
https://github.com/Alamofire/Alamofire/issues/157

So I changed this line
manager = Alamofire.Manager(configuration: configuration)

to this one
manager = Alamofire.Manager.sharedInstance

It's working now, I wanted to know if you got a more elegant way to do it.

Thanks.

**Comment by cmoulton** [comment]
It looks like the APIController isn’t getting properly retained.

In MasterViewController, add a var to retain & init it:
class MasterViewController: UITableViewController {
  var detailViewController: DetailViewController? = nil
  var spots = Array<Spot>()
  var apiController = APIController()
  ...
}

Then in getSpots remove the line that init’s it:

func getSpots()
{
  // remove this line: apiController = APIController()
  apiController.getSpots({ (fetchedSpots, error) in
  …
}

Then you should be able to use manager = Alamofire.Manager(configuration: configuration) without errors.

Thanks for catching it. I’ll update the tutorial & code to fix it ASAP but I'm stuck without decent internet for a few days.

Christina

**Comment by dams2007** [comment]
Thanks. It's working perfectly.

Damien.
