### ISSUE TITLE
Possibility to send the request with a query

### ISSUE THREAD

**Issue by dams2007** [cmoulton/SwiftParseDemo#2]
Hi Christina,
I am trying to be able to send queries instead of getting all the results.
I am thinking that with Alamofire is the easiest way to set the parameters.

So I do like that
var params = ["product" : "typeA"]
let path = "https://api.parse.com/1/classes/Products/"

manager.request(.GET, path, parameters: params)
    .responseSpotsArray { (request, response, spots, error) in
        completionHandler(spots, error)
      println(request)
    }

But I am still getting the all thing. Do you have any idea how I can manage that ?

**Comment by cmoulton** [comment]
Parse uses a weird format for their constraints like “where=_JSON params_"

This works for me by setting the params as ["where": _params_]:

```
let path = "https://api.parse.com/1/classes/Spot/"
let whereConstraint = ["Name": "My Cafe"]
manager.request(.GET, path, parameters: ["where": whereConstraint])
  .responseSpotsArray { (request, response, spots, error) in
  completionHandler(spots, error)
}
```

That’s the simplest version: constraining the values returned by the keys. There’s some more info in the docs about doing more complex queries, pagination, etc: https://www.parse.com/docs/rest/guide/#queries

**Comment by dams2007** [comment]
Thanks a lot works fine, I can send any request that I want.
I think you should implement this functionality in the project, it's kind a nice feature to have.
